version: '3.1'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn api
    volumes:
      - './:/app/red-tetris'
    ports:
      - '3001:3001'
    env_file:
      - '.env'
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn web
    volumes:
      - './:/app/red-tetris'
    ports:
      - '80:19006'
    env_file:
      - '.env'
# docker-compose up
# docker-compose up --build (if any changes made to docker files)
