version: '3.1'

services:
  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    command: npm start # If we use npm in container we need to use it in host machine server folder - not yarn
    volumes:
      - './src/server:/app/server'
      - '/app/server/node_modules'
    ports:
      - '3001:3001'
    env_file:
      - '.env' # So that we don't need to install and initialize dotenv module in server

# docker-compose up (to start backend server)
# docker-compose up --build (if any changes made to docker files)
