version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - '.:/usr/src/app/api'
      - '/usr/src/app/api/node_modules'
    ports:
      - '81:3001'
    environment:
      - NODE_ENV=development
  #docker-compose up